baseURL : https://aureli0f.github.io/Aureli0f
languageCode : fr-fr
title : Aureli0f Write Up
theme : hugo-theme-stack

defaultContentLanguage: fr

languages:
    fr :
        languageName : Français
        title: Blog d'Aureli0f 
        weight: 1
        params :
            description : Blog d'Aureli0f

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:  # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

    footer:
        since: 2023
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🔍
        subtitle: On essaie de comprendre 
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg
    
    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0
    
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

menu:
    main: []

    social:
        - identifier: ozint
          name: Ozint.eu
          url: https://ozint.eu/ozinter/4298/
          params:
              icon: ozint

        # - identifier: twitter
        #   name: Twitter
        #   url: https://twitter.com
        #   params:
        #       icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4